"use client";

import { useState } from "react";
import { HelpCircle, X } from "lucide-react";

interface HelpButtonProps {
  mode: "human" | "model";
}

export function HelpButton({ mode }: HelpButtonProps) {
  const [showHelp, setShowHelp] = useState(false);

  return (
    <>
      {showHelp && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg max-w-md w-full p-6 relative">
            <button
              onClick={() => setShowHelp(false)}
              className="absolute right-4 top-4 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
            >
              <X className="h-5 w-5" />
              <span className="sr-only">Close</span>
            </button>

            <div className="mb-4">
              <h2 className="text-lg font-semibold mb-2">
                {mode === "human"
                  ? "Human Writing Evaluation"
                  : "Model Writing Evaluation"}{" "}
                Help
              </h2>
              <div className="text-sm text-gray-600 dark:text-gray-400 space-y-2">
                {mode === "human" ? (
                  <>
                    <p>
                      In this task, you&apos;ll be shown a writing prompt and
                      two responses. Your goal is to select the response that
                      you think is higher quality writing.
                    </p>
                    <p>
                      One response was written by a human, and one was written
                      by an AI model. Try to identify which is which based on
                      the quality of the writing.
                    </p>
                    <p>
                      After making your selection, you&apos;ll see whether you
                      correctly identified the human-written response, and
                      you&apos;ll have the opportunity to provide feedback.
                    </p>
                  </>
                ) : (
                  <>
                    <p>
                      In this task, you&apos;ll be shown a writing prompt and a
                      response generated by an AI model. Your goal is to rate
                      the quality of the writing.
                    </p>
                    <p>
                      Consider factors such as creativity, coherence, grammar,
                      and how well the response addresses the prompt.
                    </p>
                    <p>
                      After rating the response, you&apos;ll have the
                      opportunity to provide feedback on what you liked or
                      didn&apos;t like about the writing.
                    </p>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      <button
        onClick={() => setShowHelp(true)}
        className="h-8 w-8 flex items-center justify-center rounded-full hover:bg-gray-100 dark:hover:bg-gray-800"
        aria-label="Help"
      >
        <HelpCircle className="h-5 w-5" />
      </button>
    </>
  );
}
